### PR TITLE
Fix usage of Sigstore env var

### LINKED ISSUE #25: The sigstore command on `add_to_pythondotorg.py` still asks for interactive input.
Unfortunately, the release script is still broken because the sigstore command on the server still blocks. Login into the machine shows that it still asks for the token in stdin.

### PR DESCRIPTION
**Pull request by di**
Fixes #25.

(cc @pablogsal)

### CODE REVIEW

**Comment by pablogsal** [comment]
Ah, apologies, it seems that my PR caused some merge problems. Could you rebase? Otherwise looks good 👍

**Comment by di** [comment]
@pablogsal Should be good now.

**Comment by di** [comment]
(note that `sigstore` will need to be upgraded on the remote machine)

**Review by pablogsal — APPROVED** [review]
LGTM 🎉

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
