### PR TITLE
Also purge source metadata files

### LINKED ISSUE #156: CDN purges don't purge all files.
Currently, we purge the CDN cache for a couple of files, but not all the files (notably missing are new files added relatively recently: sboms and sigstore signatures). https://github.com/python/release-tools/blob/master/run_release.py#L931

We should update that list, or just list all files on the download server and purge all of them.

### PR DESCRIPTION
**Pull request by sethmlarson**
Closes #156

### CODE REVIEW

**Comment by sethmlarson** [comment]
Failures appear to be unrelated to this PR.

**Comment by hugovk** [comment]
> Failures appear to be unrelated to this PR.

Yes, it was an infra update, should be fixed now: https://github.com/python/cpython/issues/122795. I've restarted the failing job.

**Comment by sethmlarson** [comment]
Job has succeeded! Thanks Hugo

**Review by hugovk — APPROVED** [review]

**Comment by hugovk** [comment]
Do you think we need to purge the things under [amd64](https://www.python.org/ftp/python/3.12.5/amd64/), [arm64](https://www.python.org/ftp/python/3.12.5/arm64/) and [win32](https://www.python.org/ftp/python/3.12.5/win32/)?

A user mentioned them in https://discuss.python.org/t/python-3-12-5-now-available/60219/5

(Doesn't block merging this now.)

**Pull request merged**
